services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      #- ./public:/var/www/html
      #- ./public:/mnt/c/Users/ronninovello/Documents/GitHub/kabum
      - .:/mnt/c/Users/ronninovello/Documents/GitHub/kabum
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network
  php:
    build: ./php
    container_name: php
    volumes:
      #- ./public:/mnt/c/Users/ronninovello/Documents/GitHub/kabum
      - .:/mnt/c/Users/ronninovello/Documents/GitHub/kabum
    depends_on:
      - db
    networks:
      - app_network
  db:
    #image: mysql:5.5.62
    image: mysql:5.6
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kabum
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql:

networks:
  app_network:
    driver: bridge