-- MySQL Script generated by MySQL Workbench
-- Mon Mar 17 07:34:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kabum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kabum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kabum` DEFAULT CHARACTER SET utf8 ;
USE `kabum` ;

-- -----------------------------------------------------
-- Table `kabum`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kabum`.`usuario` (
  `cd_usuario` INT NOT NULL AUTO_INCREMENT,
  `cd_login` INT NOT NULL,
  `ds_senha` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cd_usuario`),
  UNIQUE INDEX `cd_login_UNIQUE` (`cd_login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kabum`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kabum`.`cliente` (
  `cd_cliente` INT NOT NULL AUTO_INCREMENT,
  `nm_cliente` VARCHAR(200) NOT NULL,
  `dt_nasc` DATETIME NOT NULL,
  `nr_cpf` VARCHAR(11) NOT NULL,
  `nr_rg` VARCHAR(11) NOT NULL,
  `nr_telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cd_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`nr_cpf` ASC) ,
  UNIQUE INDEX `rg_UNIQUE` (`nr_rg` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kabum`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kabum`.`endereco` (
  `cd_endereco` INT NOT NULL AUTO_INCREMENT,
  `cd_cliente` INT NOT NULL,
  `ds_endereco` VARCHAR(300) NOT NULL,
  `nr_endereco` INT NOT NULL,
  `nm_bairro` VARCHAR(100) NOT NULL,
  `ds_complemento` VARCHAR(300) NULL,
  `nr_postal` VARCHAR(20) NOT NULL,
  `nm_cidade` VARCHAR(100) NOT NULL,
  `tp_estado` VARCHAR(2) NOT NULL,
  `nm_pais` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_endereco`),
  INDEX `fk_enderecos_clientes_idx` (`cd_cliente` ASC),
  CONSTRAINT `fk_enderecos_clientes`
    FOREIGN KEY (`cd_cliente`)
    REFERENCES `kabum`.`cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
